# Generated by Django 5.0 on 2023-12-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rchrchArtcl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('contenu', models.TextField()),
                ('pdf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Moderateurs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='favoris',
            field=models.ManyToManyField(to='rchrchArtcl.article'),
        ),
        migrations.CreateModel(
            name='Auteurs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('articles', models.ManyToManyField(to='rchrchArtcl.article')),
                ('institutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rchrchArtcl.institution')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=512)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rchrchArtcl.article')),
            ],
        ),
    ]
