# Generated by Django 5.0 on 2023-12-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rchrchArtcl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mot_cle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rchrchArtcl.article')),
            ],
        ),
    ]
