# Generated by Django 5.0 on 2024-01-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rchrchArtcl', '0003_tempmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteurs',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='article',
            name='institutions',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='article',
            name='mot_cles',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=512),
        ),
    ]
