# Generated by Django 5.0 on 2024-01-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rchrchArtcl', '0004_alter_article_auteurs_alter_article_institutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteurs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='institutions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='mot_cles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.TextField(),
        ),
    ]
