# Generated by Django 5.0 on 2024-01-09 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rchrchArtcl', '0005_alter_article_auteurs_alter_article_institutions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderateurs',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
